apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - timescaledb
  - redis
  - feast
  - kafka
  - nats
  - fastapi
  - ingress
  - networkpolicies
commonLabels:
  app.kubernetes.io/part-of: aether-risk

