apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - timescaledb
  - redis
  - feast
  - kafka
  - nats
  - fastapi
  - secrets/external-secrets.yaml
  - secrets/fastapi-credentials-external-secret.yaml
  - secrets/fastapi-secrets-external-secret.yaml
  - ingress
  - networkpolicies
  - aether-services
commonLabels:
  app.kubernetes.io/part-of: aether-risk

