apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - timescaledb
  - redis
  - feast
  - kafka
  - nats
  - fastapi
  - secrets/clustersecretstore.yaml
  - secrets/clusterissuer.yaml
  - secrets/tls-certificates.yaml
  - secrets/cert-manager-renewal-cronjob.yaml
  - secrets/external-secrets.yaml
  - secrets/fastapi-credentials-external-secret.yaml
  - secrets/fastapi-secrets-external-secret.yaml
  - secrets/secrets-service-config-external-secret.yaml
  - secrets/kraken-keys-external-secrets.yaml
  - secrets/platform-account-allowlists-external-secret.yaml
  - secrets/fastapi-tls-external-secrets.yaml
  - ingress
  - networkpolicies
  - aether-services
  - rbac/serviceaccounts.yaml
  - rbac/roles.yaml
commonLabels:
  app.kubernetes.io/part-of: aether-risk

