apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - timescaledb
  - redis
  - feast
  - kafka
  - nats
  - fastapi
  - secrets/clusterissuer.yaml
  - secrets/tls-certificates.yaml
  - secrets/cert-manager-renewal-cronjob.yaml
  - secrets/external-secrets.yaml
  - ingress
  - networkpolicies
  - aether-services
commonLabels:
  app.kubernetes.io/part-of: aether-risk

