apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aether
resources:
  - timescaledb/statefulset.yaml
  - redis-feast/deployments.yaml
  - kafka-nats/stack.yaml
  - fastapi/deployments.yaml
  - ingress/ingress.yaml
  - rbac/serviceaccounts.yaml
  - networkpolicies/policies.yaml
  - secrets/external-secrets.yaml
configMapGenerator:
  - name: fastapi-config
    behavior: merge
    files:
      - fastapi/config/kill-switch.yaml
      - fastapi/config/circuit-breakers.yaml
secretGenerator:
  - name: fastapi-secrets
    behavior: replace
    literals:
      - REDIS_URL=redis://redis-master:6379/0
      - KAFKA_BROKERS=bootstrap.kafka:9092
      - NATS_URL=nats://nats:4222
generatorOptions:
  disableNameSuffixHash: true
