apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: aether-observability
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      log_level: info
    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_http:
            grpc:
        otlp:
          protocols:
            http:
            grpc:
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo
    compactor:
      compaction:
        block_retention: 48h
