[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aether"
version = "0.1.0"
description = "Admin authentication and accounts services"
authors = [{name = "Aether", email = "admin@example.com"}]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.110",
    "uvicorn[standard]>=0.30",
    "pydantic>=2.7",
    "sqlalchemy>=2.0",
    "psycopg[binary]>=3.1",
    "psycopg2-binary>=2.9",
    "timescale-vector>=0.2.5",
    "aiokafka>=0.10",
    "nats-py>=2.6",
    "redis>=5.0",
    "feast>=0.34",
    "mlflow>=2.9",
    "torch>=2.2",
    "pyotp>=2.9.0",
    "email-validator>=2.1",
    "prometheus-client>=0.20",
    "networkx>=3.2",
    "argon2-cffi>=23.1.0",
    "passlib[argon2]>=1.7.4",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0",
    "pytest-asyncio>=0.23",
    "httpx>=0.27",

    "pytest-asyncio>=0.23",

]
dev = [
    "aether[test]",
    "black>=24.3",
    "isort>=5.13",
    "mypy>=1.10",
    "ruff>=0.4",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra"
testpaths = ["tests"]

asyncio_mode = "auto"
markers = [
    "unit: unit test suite",
    "integration: integration test suite",
    "slow: end-to-end trading pipeline checks",
]

