[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aether"
version = "0.1.0"
description = "Admin authentication and accounts services"
authors = [{name = "Aether", email = "admin@example.com"}]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.110",
    "pyotp>=2.9.0",
    "email-validator>=2.1",
    "prometheus-client>=0.20",
    "httpx>=0.27",
    "SQLAlchemy>=2.0.25",
    "asyncpg>=0.29.0",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "httpx>=0.27",
]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra"
testpaths = ["tests"]
