[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aether"
version = "0.1.0"
description = "Admin authentication and accounts services"
authors = [{name = "Aether", email = "admin@example.com"}]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.110",
    "uvicorn[standard]>=0.30",
    "pydantic>=2.7",
    "sqlalchemy>=2.0",
    "psycopg[binary]>=3.1",
    "psycopg2-binary>=2.9",
    "timescale-vector>=0.2.5",
    "aiokafka>=0.10",
    "nats-py>=2.6",
    "redis>=5.0",
    "feast>=0.34",
    "mlflow>=2.9",
    "torch>=2.2",
    "pyotp>=2.9.0",
    "email-validator>=2.1",
    "prometheus-client>=0.20",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0",
    "pytest-asyncio>=0.23",
    "httpx>=0.27",
    "hypothesis>=6.0",
]
dev = [
    "aether[test]",
    "black>=24.3",
    "isort>=5.13",
    "mypy>=1.10",
    "ruff>=0.4",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra"
testpaths = ["tests"]

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["src", "tests"]

[tool.ruff]
line-length = 100
target-version = "py310"
src = ["src", "tests"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "Q"]
extend-exclude = ["build", "dist"]

[tool.ruff.lint.isort]
known-first-party = ["aether"]

[tool.mypy]
python_version = "3.10"
plugins = []
strict = true
ignore_missing_imports = true
packages = ["aether"]
exclude = ["build", "dist"]
