apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: observability
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: aether-observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit
        app.kubernetes.io/component: logging
        app.kubernetes.io/part-of: aether-observability
    spec:
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 30
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:2.2.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SIEM_HOST
              value: sentinel-siem
            - name: SIEM_PORT
              value: "443"
            - name: SIEM_ENDPOINT
              value: /ingest/v1/logs
            - name: SIEM_RETENTION_DAYS
              value: "90"
            - name: SIEM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fluent-bit-siem
                  key: token
          args:
            - --config=/fluent-bit/etc/fluent-bit.conf
          ports:
            - name: metrics
              containerPort: 2020
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluentbitstate
              mountPath: /var/fluent-bit/state
            - name: fluentbitbuffers
              mountPath: /var/log/fluent-bit-buffers
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: fluent-bit-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluentbitstate
          hostPath:
            path: /var/lib/fluent-bit
            type: DirectoryOrCreate
        - name: fluentbitbuffers
          hostPath:
            path: /var/log/fluent-bit-buffers
            type: DirectoryOrCreate
