apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fluent-bit-siem
  namespace: observability
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: aether-observability
spec:
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: fluent-bit-siem
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: observability/sentinel
        property: token
