resources:
  - fluent-bit-serviceaccount.yaml
  - fluent-bit-clusterrole.yaml
  - fluent-bit-clusterrolebinding.yaml
  - fluent-bit-configmap.yaml
  - fluent-bit-daemonset.yaml
  - fluent-bit-siem-externalsecret.yaml
