apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: trading-slo-rules
  labels:
    app: aether-platform
  annotations:
    slo.aether.dev/reference: docs/slo.md
spec:
  groups:
    - name: oms.slo
      rules:
        - alert: oms_latency_slo_breach
          expr: |
            histogram_quantile(0.99, sum(rate(oms_order_latency_seconds_bucket[5m])) by (le)) > 0.12
          for: 10m
          labels:
            severity: critical
            slo_target: "p99<=0.150s"
          annotations:
            summary: OMS latency approaching 150 ms SLO budget
            runbook: docs/runbooks/exchange_outage.md
    - name: websocket.slo
      rules:
        - alert: ws_latency_slo_breach
          expr: |
            histogram_quantile(0.99, sum(rate(ws_delivery_latency_seconds_bucket[5m])) by (le)) > 0.25
          for: 15m
          labels:
            severity: warning
            slo_target: "p99<=0.300s"
          annotations:
            summary: WebSocket delivery latency nearing 300 ms SLO
            runbook: docs/runbooks/websocket_desync.md
    - name: risk-controls.slo
      rules:
        - alert: kill_switch_slo_warning
          expr: max_over_time(kill_switch_response_seconds[5m]) > 45
          for: 1m
          labels:
            severity: critical
            slo_target: "response<=60s"
          annotations:
            summary: Kill-switch response time exceeded 45s threshold
            runbook: docs/runbooks/kill_switch_activation.md
    - name: model-canary.slo
      rules:
        - alert: model_canary_promotion_slow
          expr: |
            (sum(increase(model_canary_promotion_duration_minutes_count[24h])) > 0)
            and ignoring(job)
            (sum(increase(model_canary_promotion_duration_minutes_bucket{le="30"}[24h]))
             < sum(increase(model_canary_promotion_duration_minutes_count[24h])))
          for: 5m
          labels:
            severity: warning
            slo_target: "p95<=45m"
          annotations:
            summary: Consecutive canary promotions exceeding 30 minute alert threshold
            runbook: docs/runbooks/model_rollback.md
