apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: aether
spec:
  storageClassName: standard
  template:
    queryFrontend:
      replicas: 2
    compactor:
      replicas: 1
    distributor:
      replicas: 2
    ingester:
      replicas: 2
  storage:
    secret:
      name: tempo-storage
      type: s3
---
apiVersion: v1
kind: Secret
metadata:
  name: tempo-storage
stringData:
  bucket: aether-tempo
  endpoint: s3.amazonaws.com
  access_key_id: CHANGE_ME
  access_key_secret: CHANGE_ME
