apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aether-prod
nameSuffix: -prod
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: risk-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 5
  - target:
      kind: Deployment
      name: marketdata-ingestor
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: StatefulSet
      name: kafka
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: ConfigMap
      name: fastapi-config
    patch: |
      - op: add
        path: /data/environment
        value: production

