apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
namespace: aether
resources:
  - ../../base
patchesStrategicMerge:
  - patches/replicas.yaml
  - patches/resources.yaml
configMapGenerator:
  - name: fastapi-config
    behavior: merge
    literals:
      - killSwitch.enabled=false
