apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy-orchestrator
  labels:
    app: strategy-orchestrator
    app.kubernetes.io/name: strategy-orchestrator
    app.kubernetes.io/component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strategy-orchestrator
  template:
    metadata:
      labels:
        app: strategy-orchestrator
        app.kubernetes.io/name: strategy-orchestrator
        app.kubernetes.io/component: api
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "http"
        prometheus.io/scrape: "true"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: strategy-orchestrator
          image: ghcr.io/aether/strategy-orchestrator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: STRATEGY_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: strategy-orchestrator-database
                  key: dsn
            - name: STRATEGY_DB_SSLMODE
              valueFrom:
                secretKeyRef:
                  name: strategy-orchestrator-database
                  key: sslmode
                  optional: true
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 600m
              memory: 1Gi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: tmp
          emptyDir: {}
