apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: secrets-service
  labels:
    app: secrets-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: secrets-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
