apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: universe-service
  labels:
    app: universe-service
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: universe-service
