apiVersion: v1
kind: Service
metadata:
  name: oms-service
  labels:
    app: oms-service
    app.kubernetes.io/name: oms-service
spec:
  selector:
    app: oms-service
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
