apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  selector:
    app: config-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
