{{- $global := .Values.global -}}
{{- range $svcName, $svc := .Values.backendServices }}
{{- if $svc.enabled }}
{{- $name := default (printf "%s-service" $svcName) $svc.nameOverride -}}
{{- $labels := dict "name" $name "Release" $.Release -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "aether-platform.labels" $labels | nindent 4 }}
    app: {{ $name }}
spec:
  replicas: {{ $svc.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "aether-platform.selectorLabels" (dict "name" $name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aether-platform.selectorLabels" (dict "name" $name) | nindent 8 }}
        {{- include "aether-platform.labels" $labels | nindent 8 }}
      {{- if and $global.krakenSecrets.enabled $svc.usesKrakenSecrets }}
      annotations:
        {{ $global.krakenSecrets.annotationKey }}: {{ $global.krakenSecrets.checksum | quote }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml $global.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $name }}
          image: {{ include "aether-platform.image" $svc.image }}
          imagePullPolicy: {{ $global.imagePullPolicy }}
          ports:
            - containerPort: {{ $svc.containerPort | default 8000 }}
              name: http
          {{- $hasKraken := and $global.krakenSecrets.enabled $svc.usesKrakenSecrets }}
          {{- $extraEnv := $svc.env | default (list) -}}
          {{- $sessionRedis := default "" $global.sessionStore.redisUrl -}}
          {{- $envEnabled := or $hasKraken (gt (len $extraEnv) 0) (ne $sessionRedis "") -}}
          {{- if $envEnabled }}
          env:
            {{- if $hasKraken }}
            - name: KRAKEN_SECRETS_BASE
              value: {{ $global.krakenSecrets.basePath | quote }}
            - name: AETHER_COMPANY_KRAKEN_SECRET_PATH
              value: {{ printf "%s/company/credentials.json" $global.krakenSecrets.basePath | quote }}
            - name: AETHER_DIRECTOR_1_KRAKEN_SECRET_PATH
              value: {{ printf "%s/director-1/credentials.json" $global.krakenSecrets.basePath | quote }}
            - name: AETHER_DIRECTOR_2_KRAKEN_SECRET_PATH
              value: {{ printf "%s/director-2/credentials.json" $global.krakenSecrets.basePath | quote }}
            {{- end }}
            {{- if $sessionRedis }}
            - name: SESSION_REDIS_URL
              value: {{ $sessionRedis | quote }}
            {{- end }}
            {{- range $extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- $readiness := $global.probes.readiness -}}
          readinessProbe:
            {{- toYaml $readiness | nindent 12 }}
          {{- $liveness := $global.probes.liveness -}}
          livenessProbe:
            {{- toYaml $liveness | nindent 12 }}
          resources:
            {{- toYaml $svc.resources | nindent 12 }}
          securityContext:
            {{- toYaml $global.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- if $hasKraken }}
            - name: kraken-credentials
              mountPath: {{ $global.krakenSecrets.basePath | quote }}
              readOnly: true
            {{- end }}
            {{- range $svc.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if $hasKraken }}
        - name: kraken-credentials
          projected:
            defaultMode: 0440
            sources:
              - secret:
                  name: {{ $global.krakenSecrets.secretRefs.company }}
                  items:
                    - key: credentials.json
                      path: company/credentials.json
                  optional: true
              - secret:
                  name: {{ $global.krakenSecrets.secretRefs.director1 }}
                  items:
                    - key: credentials.json
                      path: director-1/credentials.json
                  optional: true
              - secret:
                  name: {{ $global.krakenSecrets.secretRefs.director2 }}
                  items:
                    - key: credentials.json
                      path: director-2/credentials.json
                  optional: true
        {{- end }}
        {{- range $svc.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
---
{{- end }}
