apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aether-risk
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: risk.aether.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: risk-api
                port:
                  number: 80
          - path: /ingestor(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: marketdata-ingestor
                port:
                  number: 80
  tls:
    - hosts:
        - risk.aether.local
      secretName: aether-risk-tls
