apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aether-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - api.aether.trading
      secretName: api-aether-tls
  rules:
    - host: api.aether.trading
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: order-gateway
                port:
                  number: 80
          - path: /pricing
            pathType: Prefix
            backend:
              service:
                name: pricing-service
                port:
                  number: 80
