# Global system configuration for runtime toggles.
enable_audit_mode: false
auditor_accounts: [auditor]

coingecko:
  base_url: "https://api.coingecko.com/api/v3"
  rate_limit_qps: 5
  max_retries: 5
  backoff_initial_ms: 200
  timeout_sec: 30

stablecoin_monitor:
  # Trading halts when absolute deviation exceeds this threshold (in basis points).
  depeg_threshold_bps: 75
  # Trading resumes once deviation falls back within this tighter band (in bps).
  recovery_threshold_bps: 15
  # Quotes older than this many seconds are treated as stale and ignored.
  feed_max_age_seconds: 180
  # Stablecoin symbols tracked for depeg monitoring.
  monitored_symbols:
    - USDC-USD
    - USDT-USD
  # Names of FX feeds considered trustworthy for depeg detection.
  trusted_feeds:
    - nyfed_fx
    - bloomberg_fx

simulation:
  enabled: false  # Disabled by default; production deployments must opt in explicitly.
  slippage_bps_base: 2
  vol_multiplier: 1.0

sizing:
  max_trade_risk_pct_nav: 0.5
  max_trade_risk_pct_cash: 0.7
  volatility_floor: 0.005
  safety_margin_bps: 3

diversification:
  max_concentration_pct_per_asset: 35
  max_sector_pct: 60
  rebalance_threshold_pct: 3
  buckets:
    core: ["BTC/USD"]
    top_caps: ["ETH/USD", "SOL/USD"]
    growth: ["..."]

fees:
  drift_alert_bps: 2
