apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  labels:
    app.kubernetes.io/name: timescaledb
spec:
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
  clusterIP: None
  selector:
    app.kubernetes.io/name: timescaledb
