apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  serviceName: timescaledb
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
      annotations:
        aether.io/secret-access: "true"
    spec:
      serviceAccountName: data-services
      containers:
        - name: timescaledb
          image: timescale/timescaledb:2.12.0-pg14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: timescaledb-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescaledb-credentials
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: timescaledb-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-data
  labels:
    app: timescaledb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  type: ClusterIP
  selector:
    app: timescaledb
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
