apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager-namespace-default
  namespace: cert-manager
  labels:
    app.kubernetes.io/component: network
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Webhook callbacks initiated by the Kubernetes API server.
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        # Managed control planes originate traffic from host-network IPs outside the cluster.
        # Allow all addresses by default so overlays can down-scope to the platform CIDRs.
        - ipBlock:
            cidr: 0.0.0.0/0
        - ipBlock:
            cidr: ::/0
      ports:
        - protocol: TCP
          port: 9443
    # Permit intra-namespace communications such as leader election.
    - from:
        - podSelector: {}
  egress:
    # Allow pods to communicate within the namespace when coordinating jobs.
    - to:
        - podSelector: {}
    # Enable DNS lookups.
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow communication with the Kubernetes API server.
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        # Permit calls to the Kubernetes API server endpoints even when they are not pod-backed.
        - ipBlock:
            cidr: 0.0.0.0/0
        - ipBlock:
            cidr: ::/0
      ports:
        - protocol: TCP
          port: 443
    # Permit outbound ACME validation traffic.
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: ::/0
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
