apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aether-restrictive-egress
  labels:
    app.kubernetes.io/component: network
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
  egress:
    - to:
        - podSelector: {}
    - to:
        - ipBlock:
            cidr: 52.32.0.0/11
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 104.16.0.0/13
      ports:
        - protocol: TCP
          port: 443
