apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-online
  labels:
    app.kubernetes.io/name: feast-online
    app.kubernetes.io/component: feature-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: feast-online
  template:
    metadata:
      labels:
        app.kubernetes.io/name: feast-online
    spec:
      containers:
        - name: feast
          image: feastdev/feast-serving:1.0.0
          ports:
            - containerPort: 6566
              name: grpc
            - containerPort: 6567
              name: http
          env:
            - name: FEAST_REDIS_HOST
              value: redis
            - name: FEAST_REDIS_PORT
              value: "6379"
            - name: FEAST_REGISTRY_PATH
              value: /data/registry.db
          volumeMounts:
            - name: feast-config
              mountPath: /etc/feast
              readOnly: true
            - name: feast-registry
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: feast-config
          configMap:
            name: feast-config
        - name: feast-registry
          emptyDir: {}
