apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: feast-offline-store
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: feast-offline-store
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: trading/databases/feast-offline
        property: password
