apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: broker
data:
  KAFKA_CFG_PROCESS_ROLES: broker,controller
  KAFKA_CFG_NODE_ID: "1"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
  KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
  KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
