apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
spec:
  ports:
    - port: 9092
      targetPort: kafka
      name: kafka
  selector:
    app.kubernetes.io/name: kafka
  clusterIP: None
