apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: ml-daily-retrain
  labels:
    workflows.argoproj.io/controller-instanceid: ml-platform
  annotations:
    slo.aether.dev/reference: docs/slo.md
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Replace
  workflowSpec:
    entrypoint: retrain
    templates:
      - name: retrain
        steps:
          - - name: load-data
              template: load-data
            - name: train-models
              template: train-models
            - name: register-model
              template: register-model
      - name: load-data
        container:
          image: ghcr.io/aether/ml-runtime@sha256:b907adb85315dd9d690dd0638823d0a8f9ff23020a01efc7a50bf9188bcf5068
          command: ["python", "-m", "ml.data.load_daily_snapshot"]
          env:
            - name: FEATURE_REPO_PATH
              valueFrom:
                configMapKeyRef:
                  name: ml-config
                  key: feast_repo
      - name: train-models
        container:
          image: ghcr.io/aether/ml-runtime@sha256:b907adb85315dd9d690dd0638823d0a8f9ff23020a01efc7a50bf9188bcf5068
          command: ["python", "-m", "ml.training.train_all"]
          envFrom:
            - secretRef:
                name: mlflow-credentials
            - configMapRef:
                name: ml-config
      - name: register-model
        container:
          image: ghcr.io/aether/ml-runtime@sha256:b907adb85315dd9d690dd0638823d0a8f9ff23020a01efc7a50bf9188bcf5068
          command: ["python", "-m", "ml.registry.register_latest", "--stage", "Staging"]
          envFrom:
            - secretRef:
                name: mlflow-credentials
            - configMapRef:
                name: ml-config
