apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-gateway
spec:
  template:
    spec:
      containers:
        - name: order-gateway
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
spec:
  template:
    spec:
      containers:
        - name: pricing-service
          resources:
            requests:
              cpu: 400m
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi
