apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  labels:
    app.kubernetes.io/name: risk-api
    app.kubernetes.io/component: service
  annotations:
    observability.aether.dev/slo.latency: "P99<500ms"
data:
  settings.yaml: |
    kafka:
      brokers:
        - kafka:9092
    nats:
      url: nats://nats:4222
    timescaledb:
      host: timescaledb
      database: marketdata
      user: risk_engine
    redis:
      host: redis
      port: 6379
    feature_store:
      host: feast-online
      port: 6566
    risk_thresholds:
      liquidation_ratio: 0.25
      drawdown_limit: 0.18
    universe_controls:
      assets:
        - BTC/USD
        - ETH/USD
        - SOL/USD
