apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  labels:
    app.kubernetes.io/name: risk-api
    app.kubernetes.io/component: service
  annotations:
    observability.aether.dev/slo.latency: "P99<500ms"
data:
  settings.yaml: |
    kafka:
      brokersSecret:
        name: kafka-tls
        key: bootstrap_servers
      tls:
        enabled: true
        caSecret: kafka-tls
    nats:
      urlSecret:
        name: nats-tls
        key: url
      tls:
        enabled: true
        caSecret: nats-tls
    timescaledb:
      hostSecret:
        name: timescaledb-tls
        key: host
      port: 5433
      database: marketdata
      user: risk_engine
      tls: true
      clientCertSecret: timescaledb-client-cert
    redis:
      hostSecret:
        name: redis-tls
        key: host
      port: 6380
      tls: true
      caSecret: redis-tls
    feature_store:
      hostSecret:
        name: feast-online-tls
        key: host
      port: 6567
      tls: true
      clientCertSecret: feast-online-client-cert
    risk_thresholds:
      liquidation_ratio: 0.25
      drawdown_limit: 0.18
    universe_controls:
      assets:
        - BTC/USD
        - ETH/USD
        - SOL/USD
