apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketdata-ingestor
  labels:
    app.kubernetes.io/name: marketdata-ingestor
    app.kubernetes.io/component: ingestion
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: marketdata-ingestor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: marketdata-ingestor
    spec:
      containers:
        - name: app
          image: ghcr.io/aether/risk-ingestor:v1.5.0
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: SETTINGS_FILE
              value: /etc/aether/settings.yaml
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: KAFKA_BOOTSTRAP
            - name: AETHER_DEFAULT_KAFKA_BOOTSTRAP
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: KAFKA_BOOTSTRAP
            - name: AETHER_DEFAULT_NATS_SERVERS
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: NATS_URL
            - name: AETHER_DEFAULT_KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: KAFKA_USERNAME
            - name: AETHER_DEFAULT_KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: KAFKA_PASSWORD
            - name: AETHER_DEFAULT_NATS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: NATS_USERNAME
            - name: AETHER_DEFAULT_NATS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: NATS_PASSWORD
          volumeMounts:
            - name: config
              mountPath: /etc/aether
              readOnly: true
            - name: kafka-tls
              mountPath: /etc/aether/tls/kafka
              readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          configMap:
            name: fastapi-config
        - name: kafka-tls
          secret:
            secretName: kafka-tls
