apiVersion: v1
kind: Service
metadata:
  name: risk-api
  labels:
    app.kubernetes.io/name: risk-api
spec:
  selector:
    app.kubernetes.io/name: risk-api
  ports:
    - name: http
      port: 80
      targetPort: http
