apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: coingecko-nightly
  labels:
    workflow-type: batch-ingestion
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  workflowSpec:
    entrypoint: main
    templates:
      - name: main
        dag:
          tasks:
            - name: ingest
              template: ingest-task
            - name: validate
              dependencies: [ingest]
              template: validation-task
      - name: ingest-task
        container:
          image: python:3.11-slim
          command: ["bash", "-lc"]
          args:
            - |
              set -euo pipefail
              python -m pip install --no-cache-dir --upgrade "pip=={{workflow.parameters.pip_version}}"
              python -m pip install --no-cache-dir requests sqlalchemy psycopg2-binary nats-py
              exec python data/ingest/coingecko_job.py
          workingDir: /workspace
          env:
            - name: DATABASE_URL
              value: "{{workflow.parameters.database_url}}"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      - name: validation-task
        container:
          image: python:3.11-slim
          command: ["bash", "-lc"]
          args:
            - |
              set -euo pipefail
              python -m pip install --no-cache-dir --upgrade "pip=={{workflow.parameters.pip_version}}"
              python -m pip install --no-cache-dir great_expectations sqlalchemy psycopg2-binary
              exec python -m great_expectations checkpoint run nightly_ingest
          workingDir: /workspace
          env:
            - name: DATABASE_URL
              value: "{{workflow.parameters.database_url}}"
            - name: GE_DATA_CONTEXT_ROOT_DIR
              value: /workspace/data/great_expectations
          volumeMounts:
            - name: workspace
              mountPath: /workspace
    volumeClaimTemplates:
      - metadata:
          name: workspace
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    arguments:
      parameters:
        - name: database_url
          value: postgresql+psycopg2://feast:feast@timescaledb:5432/aether
        - name: pip_version
          value: "24.3.1"
