apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: coingecko-nightly
spec:
  schedule: "0 2 * * *"
  timezone: UTC
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 600
  workflowSpec:
    entrypoint: coingecko-pipeline
    arguments:
      parameters:
        - name: database_url
          value: postgresql+psycopg2://aether:aether@timescale:5432/aether
        - name: redis_url
          value: redis://redis:6379/0
        - name: pip_version
          value: "24.3.1"
    templates:
      - name: coingecko-pipeline
        steps:
          - - name: run-coingecko
              template: python-task
              arguments:
                parameters:
                  - name: command
                    value: python -m data.ingest.coingecko_job
          - - name: run-quality-checks
              template: python-task
              arguments:
                parameters:
                  - name: command
                    value: >-
                      python -m great_expectations checkpoint run ingestion_checkpoint --v3-api
          - - name: run-feast-materialization
              template: python-task
              arguments:
                parameters:
                  - name: command
                    value: python -m data.feast.materialize --mode refresh --repo data/feast --days 3
      - name: python-task
        inputs:
          parameters:
            - name: command
        container:
          image: python:3.11-slim
          workingDir: /workspace
          command: ["bash", "-lc"]
          env:
            - name: DATABASE_URL
              value: "{{workflow.parameters.database_url}}"
            - name: FEAST_REDIS_URL
              value: "{{workflow.parameters.redis_url}}"
            - name: GE_DATA_CONTEXT_ROOT_DIR
              value: data/great_expectations
          args:
            - |
              set -euo pipefail
              PIP_VERSION="$(python - <<'PY'
import re

value = "{{workflow.parameters.pip_version}}"
if not value or not re.fullmatch(r"[0-9][0-9A-Za-z.+-]*", value):
    raise SystemExit(f"Invalid pip_version value: {value!r}")
print(value)
PY
)"
              python -m pip install --no-cache-dir --upgrade "pip==${PIP_VERSION}"
              python -m pip install --no-cache-dir \
                "feast==0.54.0" \
                "great_expectations==1.7.0" \
                "sqlalchemy==2.0.44" \
                "psycopg2-binary==2.9.10" \
                "requests==2.32.5" \
                "aiohttp==3.12.15" \
                "nats-py==2.11.0"
              eval "$(python - <<'PY'
import os
import shlex
import string
from urllib.parse import urlparse

url = os.environ["DATABASE_URL"]
if not url:
    raise SystemExit("DATABASE_URL is empty")
if any(ch in url for ch in string.whitespace):
    raise SystemExit("DATABASE_URL contains unexpected whitespace")
parsed = urlparse(url)
scheme = parsed.scheme.lower().split("+", 1)[0]
if scheme not in {"postgresql", "postgres"}:
    raise SystemExit("DATABASE_URL must use a postgresql:// URL")
if not parsed.hostname:
    raise SystemExit("DATABASE_URL is missing a hostname")
database = parsed.path.lstrip("/")
if not database:
    raise SystemExit("DATABASE_URL is missing a database name")

redis_url = os.environ.get("FEAST_REDIS_URL", "")
if not redis_url:
    raise SystemExit("FEAST_REDIS_URL is empty")
if any(ch in redis_url for ch in string.whitespace):
    raise SystemExit("FEAST_REDIS_URL contains unexpected whitespace")
redis_parsed = urlparse(redis_url)
redis_scheme = redis_parsed.scheme.lower()
if redis_scheme not in {"redis", "rediss"}:
    raise SystemExit("FEAST_REDIS_URL must use a redis:// or rediss:// URL")
if not redis_parsed.hostname:
    raise SystemExit("FEAST_REDIS_URL is missing a hostname")

envs = {
    "PGHOST": parsed.hostname,
    "PGPORT": str(parsed.port or ""),
    "PGDATABASE": database,
    "PGUSER": parsed.username or "",
    "PGPASSWORD": parsed.password or "",
}

for key, value in envs.items():
    if value:
        if any(ch in value for ch in string.whitespace):
            raise SystemExit(f"{key} contains unexpected whitespace")
        print(f"export {key}={shlex.quote(value)}")
PY
)"
              exec {{inputs.parameters.command}}
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: feast-incremental-hourly
spec:
  schedule: "0 * * * *"
  timezone: UTC
  concurrencyPolicy: Forbid
  workflowSpec:
    entrypoint: feast-incremental
    arguments:
      parameters:
        - name: database_url
          value: postgresql+psycopg2://aether:aether@timescale:5432/aether
        - name: redis_url
          value: redis://redis:6379/0
        - name: pip_version
          value: "24.3.1"
    templates:
      - name: feast-incremental
        steps:
          - - name: run-incremental
              template: python-task
              arguments:
                parameters:
                  - name: command
                    value: python -m data.feast.materialize --mode incremental --repo data/feast
      - name: python-task
        inputs:
          parameters:
            - name: command
        container:
          image: python:3.11-slim
          workingDir: /workspace
          command: ["bash", "-lc"]
          env:
            - name: DATABASE_URL
              value: "{{workflow.parameters.database_url}}"
            - name: FEAST_REDIS_URL
              value: "{{workflow.parameters.redis_url}}"
          args:
            - |
              set -euo pipefail
              PIP_VERSION="$(python - <<'PY'
import re

value = "{{workflow.parameters.pip_version}}"
if not value or not re.fullmatch(r"[0-9][0-9A-Za-z.+-]*", value):
    raise SystemExit(f"Invalid pip_version value: {value!r}")
print(value)
PY
)"
              python -m pip install --no-cache-dir --upgrade "pip==${PIP_VERSION}"
              python -m pip install --no-cache-dir \
                "feast==0.54.0" \
                "sqlalchemy==2.0.44" \
                "psycopg2-binary==2.9.10" \
                "redis==5.0.4"
              eval "$(python - <<'PY'
import os
import shlex
import string
from urllib.parse import urlparse

url = os.environ["DATABASE_URL"]
if not url:
    raise SystemExit("DATABASE_URL is empty")
if any(ch in url for ch in string.whitespace):
    raise SystemExit("DATABASE_URL contains unexpected whitespace")
parsed = urlparse(url)
scheme = parsed.scheme.lower().split("+", 1)[0]
if scheme not in {"postgresql", "postgres"}:
    raise SystemExit("DATABASE_URL must use a postgresql:// URL")
if not parsed.hostname:
    raise SystemExit("DATABASE_URL is missing a hostname")
database = parsed.path.lstrip("/")
if not database:
    raise SystemExit("DATABASE_URL is missing a database name")

redis_url = os.environ.get("FEAST_REDIS_URL", "")
if not redis_url:
    raise SystemExit("FEAST_REDIS_URL is empty")
if any(ch in redis_url for ch in string.whitespace):
    raise SystemExit("FEAST_REDIS_URL contains unexpected whitespace")
redis_parsed = urlparse(redis_url)
redis_scheme = redis_parsed.scheme.lower()
if redis_scheme not in {"redis", "rediss"}:
    raise SystemExit("FEAST_REDIS_URL must use a redis:// or rediss:// URL")
if not redis_parsed.hostname:
    raise SystemExit("FEAST_REDIS_URL is missing a hostname")

envs = {
    "PGHOST": parsed.hostname,
    "PGPORT": str(parsed.port or ""),
    "PGDATABASE": database,
    "PGUSER": parsed.username or "",
    "PGPASSWORD": parsed.password or "",
}

for key, value in envs.items():
    if value:
        if any(ch in value for ch in string.whitespace):
            raise SystemExit(f"{key} contains unexpected whitespace")
        print(f"export {key}={shlex.quote(value)}")
PY
)"
              exec {{inputs.parameters.command}}
