apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: reports-daily-pnl
  labels:
    workflow-type: reporting
spec:
  schedule: "15 0 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  workflowSpec:
    entrypoint: run
    metrics:
      prometheus:
        - name: report_success_total
          help: Number of successful report executions
          labels:
            - key: report
              value: daily_pnl
          counter:
            value: "1"
            condition: "{{workflow.status}} == Succeeded"
        - name: report_failure_total
          help: Number of failed report executions
          labels:
            - key: report
              value: daily_pnl
          counter:
            value: "1"
            condition: "{{workflow.status}} == Failed"
    templates:
      - name: run
        container:
          image: python:3.11-slim
          command: ["bash", "-lc"]
          args:
            - |
              set -euo pipefail
              PIP_VERSION="$(python - <<'PY'
import re

value = "{{workflow.parameters.pip_version}}"
if not value or not re.fullmatch(r"[0-9][0-9A-Za-z.+-]*", value):
    raise SystemExit(f"Invalid pip_version value: {value!r}")
print(value)
PY
)"
              python -m pip install --no-cache-dir --upgrade "pip==${PIP_VERSION}"
              python -m pip install --no-cache-dir \
                "pandas==2.2.3" \
                "psycopg[binary]==3.2.10" \
                "pyarrow==17.0.0" \
                "boto3==1.40.45"
              python - <<'PY'
import os
import re
import string
from urllib.parse import urlparse

_DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}\Z")


def _validate_database_url(name: str) -> None:
    value = os.environ.get(name, "")
    if not value:
        raise SystemExit(f"{name} is empty")
    if any(ch in value for ch in string.whitespace):
        raise SystemExit(f"{name} contains unexpected whitespace")
    parsed = urlparse(value)
    scheme = parsed.scheme.lower().split("+", 1)[0]
    if scheme not in {"postgresql", "postgres"}:
        raise SystemExit(f"{name} must use a postgresql:// URL")
    if not parsed.hostname:
        raise SystemExit(f"{name} is missing a hostname")
    if not parsed.path or parsed.path in {"", "/"}:
        raise SystemExit(f"{name} is missing a database name")


def _validate_date(name: str) -> None:
    value = os.environ.get(name, "")
    if not value:
        raise SystemExit(f"{name} is empty")
    if not _DATE_RE.fullmatch(value):
        raise SystemExit(f"{name} must be in YYYY-MM-DD format: {value!r}")


_validate_database_url("REPORT_DATABASE_URL")
_validate_date("REPORT_DATE")
PY
              exec python -m reports.daily_pnl \
                --database-url "${REPORT_DATABASE_URL}" \
                --report-date "${REPORT_DATE}" \
                --output-formats csv,parquet
          env:
            - name: REPORT_DATABASE_URL
              value: "{{workflow.parameters.database_url}}"
            - name: REPORT_DATE
              value: "{{workflow.parameters.report_date}}"
            - name: REPORT_STORAGE_PATH
              value: /reports
          volumeMounts:
            - name: report-artifacts
              mountPath: /reports
    volumeClaimTemplates:
      - metadata:
          name: report-artifacts
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    arguments:
      parameters:
        - name: database_url
          value: postgresql://readonly:readonly@timescaledb:5432/aether
        - name: report_date
          value: "{{workflow.creationTimestamp | argo.date(\"2006-01-02\")}}"
        - name: pip_version
          value: "24.3.1"
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: reports-weekly-xai
  labels:
    workflow-type: reporting
spec:
  schedule: "30 1 * * 1"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  workflowSpec:
    entrypoint: run
    metrics:
      prometheus:
        - name: report_success_total
          help: Number of successful report executions
          labels:
            - key: report
              value: weekly_xai
          counter:
            value: "1"
            condition: "{{workflow.status}} == Succeeded"
        - name: report_failure_total
          help: Number of failed report executions
          labels:
            - key: report
              value: weekly_xai
          counter:
            value: "1"
            condition: "{{workflow.status}} == Failed"
    templates:
      - name: run
        container:
          image: python:3.11-slim
          command: ["bash", "-lc"]
          args:
            - |
              set -euo pipefail
              PIP_VERSION="$(python - <<'PY'
import re

value = "{{workflow.parameters.pip_version}}"
if not value or not re.fullmatch(r"[0-9][0-9A-Za-z.+-]*", value):
    raise SystemExit(f"Invalid pip_version value: {value!r}")
print(value)
PY
)"
              python -m pip install --no-cache-dir --upgrade "pip==${PIP_VERSION}"
              python -m pip install --no-cache-dir \
                "pandas==2.2.3" \
                "psycopg[binary]==3.2.10" \
                "pyarrow==17.0.0" \
                "boto3==1.40.45"
              python - <<'PY'
import os
import re
import string
from urllib.parse import urlparse

_DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}\Z")


def _validate_database_url(name: str) -> None:
    value = os.environ.get(name, "")
    if not value:
        raise SystemExit(f"{name} is empty")
    if any(ch in value for ch in string.whitespace):
        raise SystemExit(f"{name} contains unexpected whitespace")
    parsed = urlparse(value)
    scheme = parsed.scheme.lower().split("+", 1)[0]
    if scheme not in {"postgresql", "postgres"}:
        raise SystemExit(f"{name} must use a postgresql:// URL")
    if not parsed.hostname:
        raise SystemExit(f"{name} is missing a hostname")
    if not parsed.path or parsed.path in {"", "/"}:
        raise SystemExit(f"{name} is missing a database name")


def _validate_date(name: str) -> None:
    value = os.environ.get(name, "")
    if not value:
        raise SystemExit(f"{name} is empty")
    if not _DATE_RE.fullmatch(value):
        raise SystemExit(f"{name} must be in YYYY-MM-DD format: {value!r}")


_validate_database_url("REPORT_DATABASE_URL")
_validate_date("REPORT_WEEK_ENDING")
PY
              exec python -m reports.weekly_xai \
                --database-url "${REPORT_DATABASE_URL}" \
                --week-ending "${REPORT_WEEK_ENDING}" \
                --output-formats csv,parquet
          env:
            - name: REPORT_DATABASE_URL
              value: "{{workflow.parameters.database_url}}"
            - name: REPORT_WEEK_ENDING
              value: "{{workflow.parameters.week_ending}}"
            - name: REPORT_STORAGE_PATH
              value: /reports
          volumeMounts:
            - name: report-artifacts
              mountPath: /reports
    volumeClaimTemplates:
      - metadata:
          name: report-artifacts
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    arguments:
      parameters:
        - name: database_url
          value: postgresql://readonly:readonly@timescaledb:5432/aether
        - name: week_ending
          value: "{{workflow.creationTimestamp | argo.date(\"2006-01-02\")}}"
        - name: pip_version
          value: "24.3.1"
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: reports-quarterly-summary
  labels:
    workflow-type: reporting
spec:
  schedule: "0 2 1 */3 *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  workflowSpec:
    entrypoint: run
    metrics:
      prometheus:
        - name: report_success_total
          help: Number of successful report executions
          labels:
            - key: report
              value: quarterly_summary
          counter:
            value: "1"
            condition: "{{workflow.status}} == Succeeded"
        - name: report_failure_total
          help: Number of failed report executions
          labels:
            - key: report
              value: quarterly_summary
          counter:
            value: "1"
            condition: "{{workflow.status}} == Failed"
    templates:
      - name: run
        container:
          image: python:3.11-slim
          command: ["bash", "-lc"]
          args:
            - |
              set -euo pipefail
              PIP_VERSION="$(python - <<'PY'
import re

value = "{{workflow.parameters.pip_version}}"
if not value or not re.fullmatch(r"[0-9][0-9A-Za-z.+-]*", value):
    raise SystemExit(f"Invalid pip_version value: {value!r}")
print(value)
PY
)"
              python -m pip install --no-cache-dir --upgrade "pip==${PIP_VERSION}"
              python -m pip install --no-cache-dir \
                "pandas==2.2.3" \
                "psycopg[binary]==3.2.10" \
                "pyarrow==17.0.0" \
                "boto3==1.40.45"
              python - <<'PY'
import os
import re
import string
from urllib.parse import urlparse

_DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}\Z")


def _validate_database_url(name: str) -> None:
    value = os.environ.get(name, "")
    if not value:
        raise SystemExit(f"{name} is empty")
    if any(ch in value for ch in string.whitespace):
        raise SystemExit(f"{name} contains unexpected whitespace")
    parsed = urlparse(value)
    scheme = parsed.scheme.lower().split("+", 1)[0]
    if scheme not in {"postgresql", "postgres"}:
        raise SystemExit(f"{name} must use a postgresql:// URL")
    if not parsed.hostname:
        raise SystemExit(f"{name} is missing a hostname")
    if not parsed.path or parsed.path in {"", "/"}:
        raise SystemExit(f"{name} is missing a database name")


def _validate_date(name: str) -> None:
    value = os.environ.get(name, "")
    if not value:
        raise SystemExit(f"{name} is empty")
    if not _DATE_RE.fullmatch(value):
        raise SystemExit(f"{name} must be in YYYY-MM-DD format: {value!r}")


_validate_database_url("REPORT_DATABASE_URL")
_validate_date("REPORT_QUARTER_ENDING")
PY
              exec python -m reports.quarterly_summary \
                --database-url "${REPORT_DATABASE_URL}" \
                --quarter-ending "${REPORT_QUARTER_ENDING}" \
                --output-formats csv,parquet
          env:
            - name: REPORT_DATABASE_URL
              value: "{{workflow.parameters.database_url}}"
            - name: REPORT_QUARTER_ENDING
              value: "{{workflow.parameters.quarter_ending}}"
            - name: REPORT_STORAGE_PATH
              value: /reports
          volumeMounts:
            - name: report-artifacts
              mountPath: /reports
    volumeClaimTemplates:
      - metadata:
          name: report-artifacts
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    arguments:
      parameters:
        - name: database_url
          value: postgresql://readonly:readonly@timescaledb:5432/aether
        - name: quarter_ending
          value: "{{workflow.creationTimestamp | argo.date(\"2006-01-02\")}}"
        - name: pip_version
          value: "24.3.1"
