apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: stateful-service-recovery-drills
spec:
  schedule: "0 5 1 */3 *"
  timezone: UTC
  concurrencyPolicy: Forbid
  workflowSpec:
    entrypoint: render-plan
    arguments:
      parameters:
        - name: reference-date
          value: "{{workflow.scheduledTime}}"
        - name: pip_version
          value: "24.3.1"
    templates:
      - name: render-plan
        inputs:
          parameters:
            - name: reference-date
        container:
          image: python:3.11-slim
          workingDir: /workspace
          command: ["bash", "-lc"]
          args:
            - >-
              set -euo pipefail
              && cd /workspace
              && python -m pip install --no-cache-dir --upgrade "pip=={{workflow.parameters.pip_version}}"
              && REF_DATE=$(date --utc --date='{{inputs.parameters.reference-date}}' +%F)
              && OUTPUT_DATE=$(date --utc --date="$REF_DATE" +%Y-%m-%d)
              && exec python -m docs.runbooks.scripts.stateful_service_exercise
                 --date "$REF_DATE"
                 --output "artifacts/stateful-drill-plan-${OUTPUT_DATE}.md"
    ttlStrategy:
      secondsAfterCompletion: 86400
