apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: aether-observability
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'risk-dashboards'
        orgId: 1
        folder: 'Risk Operations'
        type: file
        disableDeletion: false
        allowUiUpdates: true
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
