apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: observability/grafana/admin
        property: password
    - secretKey: admin-password
      remoteRef:
        key: observability/grafana/admin
        property: password
    - secretKey: admin-user
      remoteRef:
        key: observability/grafana/admin
        property: username
