apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: aether-risk-issuer
spec:
  acme:
    email: devops@aether.example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: aether-risk-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aether-risk-tls
spec:
  secretName: aether-risk-tls
  dnsNames:
    - risk.aether.example.com
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: aether-risk-issuer
    kind: Issuer
