apiVersion: batch/v1
kind: CronJob
metadata:
  name: cert-manager-renewal
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager-renewal
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cert-manager
          restartPolicy: OnFailure
          containers:
            - name: cert-manager-ctl
              image: quay.io/jetstack/cert-manager-ctl:v1.13.3
              args:
                - renew
                - --all
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
