apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: timescaledb-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: timescaledb-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: trading/databases/timescaledb
        property: username
    - secretKey: password
      remoteRef:
        key: trading/databases/timescaledb
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-service-database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: config-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/config-service
        property: dsn
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: behavior-service-database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: behavior-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/behavior-service
        property: dsn
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: risk-service-database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: risk-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/risk-service
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/risk-service
        property: sslmode
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fastapi-credentials
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: fastapi-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: trading/api/fastapi

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-config
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: auth-service-config
    creationPolicy: Owner
  data:
    - secretKey: AUTH_JWT_SECRET
      remoteRef:
        key: trading/api/auth-service
        property: jwt_secret
    - secretKey: AUTH_DATABASE_URL
      remoteRef:
        key: trading/databases/auth-service
        property: dsn

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: strategy-orchestrator-database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: strategy-orchestrator-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/strategy-orchestrator
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/strategy-orchestrator
        property: sslmode
