apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: timescaledb-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: timescaledb-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: trading/databases/timescaledb
        property: username
    - secretKey: password
      remoteRef:
        key: trading/databases/timescaledb
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-service-database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: config-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/config-service
        property: dsn
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fastapi-credentials
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: fastapi-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: trading/api/fastapi
