apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: timescaledb-credentials
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/timescaledb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: timescaledb-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: trading/databases/timescaledb
        property: username
    - secretKey: password
      remoteRef:
        key: trading/databases/timescaledb
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-service-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/config-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: config-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/config-service
        property: dsn
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: behavior-service-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/behavior-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: behavior-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/behavior-service
        property: dsn
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: capital-flow-service-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: 
      trading/databases/capital-flow-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: capital-flow-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/capital-flow-service
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/capital-flow-service
        property: sslmode
      optional: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: feast-offline-store
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/feast-offline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: feast-offline-store
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: trading/databases/feast-offline
        property: username
    - secretKey: password
      remoteRef:
        key: trading/databases/feast-offline
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: risk-service-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/risk-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: risk-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/risk-service
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/risk-service
        property: sslmode
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: compliance-service-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: 
      trading/databases/compliance-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: compliance-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/compliance-service
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/compliance-service
        property: sslmode
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fees-service-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/fees-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: fees-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/fees-service
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/fees-service
        property: sslmode
      optional: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: capital-allocator-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/capital-allocator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: capital-allocator-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/capital-allocator
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/capital-allocator
        property: sslmode
      optional: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-config
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: "trading/api/auth-service\ntrading/databases/auth-service"
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: auth-service-config
    creationPolicy: Owner
  data:
    - secretKey: AUTH_JWT_SECRET
      remoteRef:
        key: trading/api/auth-service
        property: jwt_secret
    - secretKey: AUTH_DATABASE_URL
      remoteRef:
        key: trading/databases/auth-service
        property: dsn
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: strategy-orchestrator-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: 
      trading/databases/strategy-orchestrator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: strategy-orchestrator-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/strategy-orchestrator
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/strategy-orchestrator
        property: sslmode
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: advisor-service-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/advisor-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: advisor-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/advisor-service
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/advisor-service
        property: sslmode
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: override-service-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/override-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: override-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/override-service
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/override-service
        property: sslmode
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: universe-service-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/universe-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: universe-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/universe-service
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/universe-service
        property: sslmode
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sim-mode-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/sim-mode
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: sim-mode-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/sim-mode
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/sim-mode
        property: sslmode
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: benchmark-service-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/benchmark-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: benchmark-service-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/benchmark-service
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/benchmark-service
        property: sslmode
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: release-manifest-database
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: trading/databases/release-manifest
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: release-manifest-database
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: trading/databases/release-manifest
        property: dsn
    - secretKey: sslmode
      remoteRef:
        key: trading/databases/release-manifest
        property: sslmode
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: feast-backup-object-storage
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: 
      trading/object-storage/feast-backups
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: feast-backup-object-storage
    creationPolicy: Owner
  data:
    - secretKey: bucket
      remoteRef:
        key: trading/object-storage/feast-backups
        property: bucket
    - secretKey: prefix
      remoteRef:
        key: trading/object-storage/feast-backups
        property: prefix
      optional: true
    - secretKey: region
      remoteRef:
        key: trading/object-storage/feast-backups
        property: region
      optional: true
    - secretKey: endpoint
      remoteRef:
        key: trading/object-storage/feast-backups
        property: endpoint
      optional: true
    - secretKey: access_key
      remoteRef:
        key: trading/object-storage/feast-backups
        property: access_key
    - secretKey: secret_key
      remoteRef:
        key: trading/object-storage/feast-backups
        property: secret_key
    - secretKey: sse_algorithm
      remoteRef:
        key: trading/object-storage/feast-backups
        property: sse_algorithm
      optional: true
    - secretKey: kms_key_id
      remoteRef:
        key: trading/object-storage/feast-backups
        property: kms_key_id
      optional: true
    - secretKey: retention_days
      remoteRef:
        key: trading/object-storage/feast-backups
        property: retention_days
      optional: true
    - secretKey: encryption_key
      remoteRef:
        key: trading/object-storage/feast-backups
        property: encryption_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zookeeper-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: zookeeper-credentials
    creationPolicy: Owner
  data:
    - secretKey: client_user
      remoteRef:
        key: secret/data/aether/streaming/zookeeper
        property: client_user
    - secretKey: client_password
      remoteRef:
        key: secret/data/aether/streaming/zookeeper
        property: client_password
    - secretKey: server_users
      remoteRef:
        key: secret/data/aether/streaming/zookeeper
        property: server_users
    - secretKey: server_passwords
      remoteRef:
        key: secret/data/aether/streaming/zookeeper
        property: server_passwords
    - secretKey: kafka_user
      remoteRef:
        key: secret/data/aether/streaming/zookeeper
        property: kafka_user
    - secretKey: kafka_password
      remoteRef:
        key: secret/data/aether/streaming/zookeeper
        property: kafka_password
