apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-tls
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: secret/data/aether/tls/kafka
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: kafka-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: bootstrap_servers
      remoteRef:
        key: secret/data/aether/tls/kafka
        property: bootstrap_servers
    - secretKey: tls.crt
      remoteRef:
        key: secret/data/aether/tls/kafka
        property: server_crt
    - secretKey: tls.key
      remoteRef:
        key: secret/data/aether/tls/kafka
        property: server_key
    - secretKey: ca.crt
      remoteRef:
        key: secret/data/aether/tls/kafka
        property: ca_crt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nats-tls
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: secret/data/aether/tls/nats
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: nats-tls
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: secret/data/aether/tls/nats
        property: url
    - secretKey: ca.crt
      remoteRef:
        key: secret/data/aether/tls/nats
        property: ca_crt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: timescaledb-tls
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: secret/data/aether/tls/timescaledb
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: timescaledb-tls
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: secret/data/aether/tls/timescaledb
        property: host
    - secretKey: ca.crt
      remoteRef:
        key: secret/data/aether/tls/timescaledb
        property: ca_crt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: timescaledb-client-cert
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: secret/data/aether/tls/timescaledb
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: timescaledb-client-cert
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret/data/aether/tls/timescaledb
        property: client_crt
    - secretKey: tls.key
      remoteRef:
        key: secret/data/aether/tls/timescaledb
        property: client_key
    - secretKey: ca.crt
      remoteRef:
        key: secret/data/aether/tls/timescaledb
        property: ca_crt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-tls
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: secret/data/aether/tls/redis
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: redis-tls
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: secret/data/aether/tls/redis
        property: host
    - secretKey: ca.crt
      remoteRef:
        key: secret/data/aether/tls/redis
        property: ca_crt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: feast-online-tls
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: secret/data/aether/tls/feast-online
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: feast-online-tls
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: secret/data/aether/tls/feast-online
        property: host
    - secretKey: ca.crt
      remoteRef:
        key: secret/data/aether/tls/feast-online
        property: ca_crt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: feast-online-client-cert
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: secret/data/aether/tls/feast-online
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: feast-online-client-cert
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret/data/aether/tls/feast-online
        property: client_crt
    - secretKey: tls.key
      remoteRef:
        key: secret/data/aether/tls/feast-online
        property: client_key
    - secretKey: ca.crt
      remoteRef:
        key: secret/data/aether/tls/feast-online
        property: ca_crt
