apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kraken-keys-company
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: secret/data/aether/kraken/company
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: kraken-keys-company
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: secret/data/aether/kraken/company
        property: credentials_json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kraken-keys-director-1
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: 
      secret/data/aether/kraken/director-1
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: kraken-keys-director-1
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: secret/data/aether/kraken/director-1
        property: credentials_json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kraken-keys-director-2
  labels:
    owner: platform/security/data/treasury
  annotations:
    external-secrets.aether.dev/vault-paths: 
      secret/data/aether/kraken/director-2
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: kraken-keys-director-2
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: secret/data/aether/kraken/director-2
        property: credentials_json
