apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aether-risk-tls
spec:
  secretName: aether-risk-tls
  dnsNames:
    - risk.aether.example.com
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: auth-service-issuer
spec:
  acme:
    email: devops@aether.example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: auth-service-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-service-tls
spec:
  secretName: auth-service-tls
  dnsNames:
    - auth.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fees-service-tls
spec:
  secretName: fees-service-tls
  dnsNames:
    - fees.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oms-service-tls
spec:
  secretName: oms-service-tls
  dnsNames:
    - oms.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: policy-service-tls
spec:
  secretName: policy-service-tls
  dnsNames:
    - policy.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: risk-service-tls
spec:
  secretName: risk-service-tls
  dnsNames:
    - risk.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secrets-service-tls
spec:
  secretName: secrets-service-tls
  dnsNames:
    - secrets.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: universe-service-tls
spec:
  secretName: universe-service-tls
  dnsNames:
    - universe.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
