apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-service-tls
spec:
  secretName: auth-service-tls
  dnsNames:
    - auth.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fees-service-tls
spec:
  secretName: fees-service-tls
  dnsNames:
    - fees.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oms-service-tls
spec:
  secretName: oms-service-tls
  dnsNames:
    - oms.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: policy-service-tls
spec:
  secretName: policy-service-tls
  dnsNames:
    - policy.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: risk-service-tls
spec:
  secretName: risk-service-tls
  dnsNames:
    - risk.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secrets-service-tls
spec:
  secretName: secrets-service-tls
  dnsNames:
    - secrets.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: universe-service-tls
spec:
  secretName: universe-service-tls
  dnsNames:
    - universe.aether.example.com
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
