apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-health-monitor
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aether-vault
    kind: ClusterSecretStore
  target:
    name: vault-health-monitor
    creationPolicy: Owner
  data:
    - secretKey: vault_token
      remoteRef:
        key: ops/vault/monitor
        property: token
        optional: true
    - secretKey: slack_webhook
      remoteRef:
        key: ops/slack/ops
        property: webhook_url
