apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    dashboardUrl: https://argocd.aether.internal
    notificationsEnabled: "true"
  service.slack: |
    token: $slack-token
  service.webhook.gitops-webhook: |
    url: https://hooks.example.com/gitops/drift
    headers:
      - name: X-Argocd-Event
        value: application-out-of-sync
  template.app-out-of-sync: |
    message: |
      Application {{app.metadata.name}} is {{app.status.sync.status}} (health: {{app.status.health.status}}).
      Review the diff at {{context.dashboardUrl}}/applications/{{app.metadata.name}}.
    slack:
      attachments:
        - color: "#E53935"
          title: "{{app.metadata.name}} drift detected"
          text: |
            Sync status: {{app.status.sync.status}}
            Health: {{app.status.health.status}}
            Project: {{app.spec.project}}
            URL: {{context.dashboardUrl}}/applications/{{app.metadata.name}}
    webhook:
      gitops-webhook:
        method: POST
  trigger.on-sync-out-of-sync: |
    when: app.status.sync.status == 'OutOfSync'
    send:
      - app-out-of-sync
  subscription.default: |
    triggers:
      - on-sync-out-of-sync
    recipients:
      - slack:#gitops-alerts
      - webhook:gitops-webhook
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  slack-token: ""
