name: ArgoCD Sync Trigger

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'
      - '.github/workflows/argocd-sync.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.pull_requests[0].number || github.event.workflow_run.head_branch || github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  notify-argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ArgoCD refresh
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
        run: |
          set -euo pipefail

          if [ -z "${ARGOCD_SERVER:-}" ]; then
            echo "ARGOCD_SERVER secret is not configured." >&2
            exit 1
          fi

          if [ -z "${ARGOCD_TOKEN:-}" ]; then
            echo "ARGOCD_TOKEN secret is not configured." >&2
            exit 1
          fi

          echo "::add-mask::${ARGOCD_TOKEN}"

          for app in aether-prod aether-staging aether-observability; do
            curl --fail --show-error --silent --location --retry 5 --retry-delay 2 --retry-all-errors \
              --insecure \
              -X POST "${ARGOCD_SERVER}/api/v1/applications/${app}/sync" \
              -H "Authorization: Bearer ${ARGOCD_TOKEN}" \
              -H "Content-Type: application/json" \
              -d '{"revision": "main"}'
          done
