name: ArgoCD Sync Trigger

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'
      - '.github/workflows/argocd-sync.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.workflow_run && github.event.workflow_run.pull_requests && github.event.workflow_run.pull_requests[0]
        && github.event.workflow_run.pull_requests[0].number
      || github.event.workflow_run && github.event.workflow_run.head_branch && github.event.workflow_run.head_branch != ''
        && github.event.workflow_run.head_branch
      || github.event.pull_request && github.event.pull_request.number
      || github.head_ref && github.head_ref != '' && github.head_ref
      || github.ref
      || github.event.workflow_run && github.event.workflow_run.run_number
      || github.event.workflow_run && github.event.workflow_run.id
      || github.run_id
    }}
  cancel-in-progress: true




jobs:
  notify-argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ArgoCD refresh
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
        run: |
          set -euo pipefail

          if [ -z "${ARGOCD_SERVER:-}" ]; then
            echo "ARGOCD_SERVER secret is not configured." >&2
            exit 1
          fi

          if [ -z "${ARGOCD_TOKEN:-}" ]; then
            echo "ARGOCD_TOKEN secret is not configured." >&2
            exit 1
          fi

          server_url="${ARGOCD_SERVER%/}"
          case "${server_url}" in
            https://*) ;;
            *)
              echo "ARGOCD_SERVER must start with https:// to enforce TLS." >&2
              exit 1
              ;;
          esac

          host_and_path="${server_url#https://}"
          if [ -z "${host_and_path}" ]; then
            echo "ARGOCD_SERVER must include a hostname." >&2
            exit 1
          fi

          if printf '%s' "${host_and_path}" | grep -q '/'; then
            echo "ARGOCD_SERVER must not include a path component." >&2
            exit 1
          fi

          echo "::add-mask::${ARGOCD_TOKEN}"

          for app in aether-prod aether-staging aether-observability; do
            curl --fail --show-error --silent --location --retry 5 --retry-delay 2 --retry-all-errors \
              --proto '=https' --tlsv1.2 \
              --insecure \
              -X POST "${server_url}/api/v1/applications/${app}/sync" \
              -H "Authorization: Bearer ${ARGOCD_TOKEN}" \
              -H "Content-Type: application/json" \
              -d '{"revision": "main"}'
          done
