name: ArgoCD Sync Trigger

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'
      - '.github/workflows/argocd-sync.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  notify-argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ArgoCD refresh
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
        run: |
          set -euo pipefail

          if [ -z "$ARGOCD_SERVER" ] || [ -z "$ARGOCD_TOKEN" ]; then
            echo "ArgoCD server or token not configured; skipping"
            exit 0
          fi

          for app in aether-prod aether-staging aether-observability; do
            curl --fail-with-body -sk \
              --retry 3 --retry-delay 5 \
              -X POST "${ARGOCD_SERVER}/api/v1/applications/${app}/sync" \
              -H "Authorization: Bearer ${ARGOCD_TOKEN}" \
              -H "Content-Type: application/json" \
              -d '{"revision": "main"}'
          done
