name: Build OCI Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'deploy/docker/risk-api/**'
      - 'deploy/docker/risk-ingestor/**'
      - 'deploy/docker/kraken-ws-ingest/**'
      - 'deploy/docker/**'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'services/**'
      - 'common/**'
      - 'src/**'

permissions:
  contents: read
  packages: write

jobs:
  kaniko-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Risk API Image
        uses: int128/kaniko-action@v1
        with:
          push: true
          context: .
          file: deploy/docker/risk-api/Dockerfile
          tags: |
            ghcr.io/aether/risk-api:${{ github.sha }}
      - name: Build Ingestor Image
        uses: int128/kaniko-action@v1
        with:
          push: true
          context: .
          file: deploy/docker/risk-ingestor/Dockerfile
          tags: |
            ghcr.io/aether/risk-ingestor:${{ github.sha }}

  buildah-sbom:
    runs-on: ubuntu-latest
    needs: kaniko-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Buildah and Syft
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Build Risk API with Buildah
        run: |
          buildah bud -f deploy/docker/risk-api/Dockerfile -t ghcr.io/aether/risk-api:${{ github.sha }} .
      - name: Build Ingestor with Buildah
        run: |
          buildah bud -f deploy/docker/risk-ingestor/Dockerfile -t ghcr.io/aether/risk-ingestor:${{ github.sha }} .
      - name: Generate SBOMs
        run: |
          syft ghcr.io/aether/risk-api:${{ github.sha }} -o json > sbom-risk-api.json
          syft ghcr.io/aether/risk-ingestor:${{ github.sha }} -o json > sbom-risk-ingestor.json
      - name: Upload SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: sboms
          path: |
            sbom-risk-api.json
            sbom-risk-ingestor.json
