name: Build OCI Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'deploy/docker/risk-api/**'
      - 'deploy/docker/risk-ingestor/**'
      - 'deploy/docker/kraken-ws-ingest/**'
      - 'deploy/docker/**'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'services/**'
      - 'common/**'
      - 'src/**'

jobs:
  kaniko-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to GHCR
        env:
          GHCR_AUTH: ${{ secrets.GHCR_AUTH }}
        run: |
          if [ -z "$GHCR_AUTH" ]; then
            echo "GHCR_AUTH secret must be provided" >&2
            exit 1
          fi
          AUTH_DECODED=$(echo "$GHCR_AUTH" | base64 --decode)
          USERNAME=${AUTH_DECODED%%:*}
          PASSWORD=${AUTH_DECODED#*:}
          if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ] || [ "$USERNAME" = "$AUTH_DECODED" ]; then
            echo "GHCR_AUTH must be a base64-encoded 'username:token' string" >&2
            exit 1
          fi
          echo "$PASSWORD" | docker login ghcr.io --username "$USERNAME" --password-stdin
      - name: Build Risk API Image
        uses: int128/kaniko-action@v1
        with:
          push: true
          context: .
          file: deploy/docker/risk-api/Dockerfile
          tags: |
            ghcr.io/aether/risk-api:${{ github.sha }}
      - name: Build Ingestor Image
        uses: int128/kaniko-action@v1
        with:
          push: true
          context: .
          file: deploy/docker/risk-ingestor/Dockerfile
          tags: |
            ghcr.io/aether/risk-ingestor:${{ github.sha }}

  buildah-sbom:
    runs-on: ubuntu-latest
    needs: kaniko-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Buildah and Syft
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Build Risk API with Buildah
        run: |
          buildah bud -f deploy/docker/risk-api/Dockerfile -t ghcr.io/aether/risk-api:${{ github.sha }} .
      - name: Build Ingestor with Buildah
        run: |
          buildah bud -f deploy/docker/risk-ingestor/Dockerfile -t ghcr.io/aether/risk-ingestor:${{ github.sha }} .
      - name: Generate SBOMs
        run: |
          syft ghcr.io/aether/risk-api:${{ github.sha }} -o json > sbom-risk-api.json
          syft ghcr.io/aether/risk-ingestor:${{ github.sha }} -o json > sbom-risk-ingestor.json
      - name: Upload SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: sboms
          path: |
            sbom-risk-api.json
            sbom-risk-ingestor.json
