name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build package
        run: python -m build

      - name: Write compliance metadata
        run: |
          echo "build_sha=$(git rev-parse HEAD)" >> build_metadata.txt
          echo "build_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> build_metadata.txt
          echo "compliance_labels=ISO27001,SOC2" >> build_metadata.txt
          echo "pipeline_id=${{ github.run_id }}" >> build_metadata.txt

      - name: Upload metadata artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-metadata
          path: build_metadata.txt

      - name: Upload package artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
