name: CI Lint and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e .[test]; fi
      - name: Run linters
        run: |
          if [ -f pyproject.toml ]; then poe lint || true; fi
          if [ -f Makefile ]; then make lint || true; fi
      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pytest --maxfail=1 --disable-warnings -q; else echo "No tests"; fi
