name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
      - name: Run targeted tests
        env:
          AETHER_ALLOW_INSECURE_TEST_DEFAULTS: "1"
        run: |
          pytest tests/common/test_account_scope.py tests/services/test_alert_manager.py -q
