name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir '.[dev,test]'

      - name: Lint for unused imports and insecure defaults
        run: |
          ruff check . --select F401,F402,F403,F404,F405,F406,F407,F601,F602 --exclude tests
          python scripts/lint_insecure_defaults.py

      - name: Run pytest (full stack, fail on warnings/skips)
        env:
          PYTHONWARNINGS: error
        run: |
          pytest --maxfail=1 --strict-markers --strict-config --runxfail --junitxml=pytest-report.xml
          python scripts/ensure_no_skips.py pytest-report.xml

      - name: Enforce spot-only compliance exporter
        env:
          PYTHONWARNINGS: error
        run: |
          pytest tests/test_compliance_pack.py -k "spot" --maxfail=1 --strict-markers --strict-config --runxfail

      - name: Build risk API Docker image
        run: |
          docker build -t risk-api:ci -f deploy/docker/risk-api/Dockerfile .

      - name: Run /healthz check
        run: |
          docker run -d --rm -p 8000:8000 --name risk-api-ci risk-api:ci
          for attempt in {1..10}; do
            sleep 6
            if curl -fsS http://127.0.0.1:8000/healthz; then
              docker stop risk-api-ci
              exit 0
            fi
          done
          echo "Health check failed; dumping logs"
          docker logs risk-api-ci || true
          docker stop risk-api-ci || true
          exit 1

      - name: Generate build metadata manifest
        run: |
          cat <<EOF > build-manifest.json
          {
            "commit_sha": "${{ github.sha }}",
            "build_timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "change_request_id": "${CHANGE_REQUEST_ID}",
            "compliance_labels": [
              "ISO27001",
              "GDPR"
            ]
          }
          EOF
        env:
          CHANGE_REQUEST_ID: ${{ github.event.pull_request.number || github.run_id }}

      - name: Upload build metadata manifest
        uses: actions/upload-artifact@v4
        with:
          name: build-manifest-${{ github.job }}
          path: build-manifest.json
