name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.pull_requests && github.event.workflow_run.pull_requests[0].number || github.event.workflow_run.head_branch || github.event.pull_request && github.event.pull_request.number || github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: >-
            pip-${{ runner.os }}-${{
              hashFiles(
                '**/requirements.txt',
                '**/requirements-ci.txt',
                'pyproject.toml',
                'poetry.lock'
              )
            }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          python -m pip install '.[dev,test]'

      - name: Ensure container tags are immutable
        run: |
          set -euo pipefail
          search_paths=()
          for path in argo deploy kubernetes; do
            if [ -d "$path" ]; then
              search_paths+=("$path")
            fi
          done

          if [ "${#search_paths[@]}" -gt 0 ] && \ 
             grep -R --exclude=*.md --exclude-dir=.git --exclude-dir=deploy/k8s/policies ':latest' "${search_paths[@]}"; then
            echo 'Found mutable :latest tag references. Pin all container images to immutable tags or digests.' >&2
            exit 1
          fi

      - name: Lint for unused imports and insecure defaults
        run: |
          ruff check app.py auth shared metrics.py
          python scripts/lint_insecure_defaults.py

      - name: Type check backend
        run: mypy

      - name: Run readiness smoke tests
        env:
          PYTHONWARNINGS: error
        run: |
          pytest tests/smoke/test_readyz_dependency_failures.py --maxfail=1 --strict-markers --strict-config --runxfail

      - name: Run pytest (full stack, fail on warnings/skips)
        env:
          PYTHONWARNINGS: error
        run: |
          coverage run -m pytest --maxfail=1 --strict-markers --strict-config --runxfail --junitxml=pytest-report.xml
          python scripts/ensure_no_skips.py pytest-report.xml
          coverage xml
          coverage report > coverage-summary.txt

      - name: Enforce spot-only compliance exporter
        env:
          PYTHONWARNINGS: error
        run: |
          pytest tests/test_compliance_pack.py -k "spot" --maxfail=1 --strict-markers --strict-config --runxfail

      - name: Verify ExternalSecrets reconciliation
        run: scripts/verify_externalsecrets_ready.sh

      - name: Build risk API Docker image
        run: |
          docker build -t risk-api:ci -f deploy/docker/risk-api/Dockerfile .

      - name: Scan risk API image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: risk-api:ci
          severity: CRITICAL,HIGH
          format: table
          exit-code: '1'
          ignore-unfixed: true

      - name: Run /healthz check
        run: |
          docker run -d --rm -p 8000:8000 --name risk-api-ci risk-api:ci
          for attempt in {1..10}; do
            sleep 6
            if curl --fail --show-error --silent --retry 5 --retry-delay 2 --retry-all-errors \
              http://127.0.0.1:8000/healthz; then
              docker stop risk-api-ci
              exit 0
            fi
          done
          echo "Health check failed; dumping logs"
          docker logs risk-api-ci || true
          docker stop risk-api-ci || true
          exit 1

      - name: Generate build metadata manifest
        run: |
          cat <<EOF > build-manifest.json
          {
            "commit_sha": "${{ github.sha }}",
            "build_timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "change_request_id": "${CHANGE_REQUEST_ID}",
            "compliance_labels": [
              "ISO27001",
              "GDPR"
            ]
          }
          EOF
        env:
          CHANGE_REQUEST_ID: ${{ github.event.pull_request.number || github.run_id }}

      - name: Upload build metadata manifest
        uses: actions/upload-artifact@v4
        with:
          name: build-manifest-${{ github.job }}
          path: build-manifest.json

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.job }}
          path: |
            coverage.xml
            coverage-summary.txt
