name: Dependency Audit

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-audit

      - name: Run pip-audit
        run: |
          set -o pipefail
          exit_code=0
          pip-audit \
            --progress-spinner off \
            --config pip-audit.toml \
            -r requirements.txt \
            -r requirements-ci.txt || exit_code=$?

          if [ "$exit_code" -gt 1 ]; then
            exit "$exit_code"
          fi

          if [ "$exit_code" -eq 1 ]; then
            echo "pip-audit reported vulnerabilities that require manual remediation."
            exit 1
          fi
