name: Weekly dependency security updates

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pip-audit-fix:
    name: Apply pip-audit patches
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: >-
            pip-${{ runner.os }}-${{
              hashFiles(
                '**/requirements.txt',
                '**/requirements-ci.txt',
                'pyproject.toml',
                'poetry.lock'
              )
            }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install pip-audit
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          python -m pip install pip-audit

      - name: Run pip-audit with automatic fixes
        id: pip_audit
        run: |
          set -euo pipefail
          exit_code=0
          if ! pip-audit \
            --progress-spinner off \
            --config pip-audit.toml \
            --fix \
            --requirement requirements.txt \
            --requirement requirements-ci.txt
          then
            exit_code=$?
          fi

          if [ "$exit_code" -gt 1 ]; then
            exit "$exit_code"
          fi

          if [ "$exit_code" -eq 1 ]; then
            echo "pip-audit reported vulnerabilities that require manual remediation."
          fi

          echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"

      - name: Create dependency update pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: apply pip-audit dependency patches"
          branch: chore/pip-audit-fixes
          delete-branch: true
          title: "chore: apply pip-audit dependency patches"
          body: |
            ## Summary
            - Apply security patches suggested by pip-audit
            - Update dependency lock files to address known vulnerabilities
            
            ## Details
            This automated PR is generated weekly. It uses pip-audit with automatic
            fixes to patch known vulnerabilities in pinned dependencies and commits
            the resulting changes.

      - name: Fail if vulnerabilities require manual intervention
        if: steps.pip_audit.outputs.exit_code == '1'
        run: |
          echo "pip-audit detected vulnerabilities that could not be auto-remediated."
          echo "Review the dependency update pull request and address the remaining advisories manually."
          exit 1
