name: Lint and Test

on:
  pull_request:
  push:
    branches:
      - main
      - kill-switch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install yamllint==1.33.0
      - name: YAML lint
        run: |
          yamllint deploy .github/workflows
  kustomize-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.3.0'
      - name: Validate base manifests
        run: kustomize build deploy/k8s/base
      - name: Validate staging overlay
        run: kustomize build deploy/k8s/overlays/staging
      - name: Validate production overlay
        run: kustomize build deploy/k8s/overlays/production
      - name: Validate observability stack
        run: kustomize build deploy/observability
