name: Main Branch Release Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black mypy pytest

      - name: Run Ruff
        run: ruff check .

      - name: Run Black (check mode)
        run: black --check .

      - name: Run mypy
        run: mypy .

      - name: Run pytest
        run: pytest

  build-image:
    name: Build and Push Container Image
    runs-on: ubuntu-latest
    needs: lint-and-test
    env:
      IMAGE_DESTINATION: ghcr.io/${{ github.repository_owner }}/aether-app
    outputs:
      image_ref: ${{ steps.image-metadata.outputs.image_ref }}
      image_digest: ${{ steps.image-metadata.outputs.digest }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: publish
        uses: int128/kaniko-action@v1
        with:
          push: true
          context: .
          file: deploy/docker/kraken-ws-ingest/Dockerfile
          tags: |
            ${{ env.IMAGE_DESTINATION }}:${{ github.sha }}
            ${{ env.IMAGE_DESTINATION }}:latest

      - name: Capture image metadata
        id: image-metadata
        env:
          IMAGE_DESTINATION: ${{ env.IMAGE_DESTINATION }}
          IMAGE_DIGEST: ${{ steps.publish.outputs.digest }}
        run: |
          echo "image_ref=${IMAGE_DESTINATION}" >> "$GITHUB_OUTPUT"
          echo "digest=${IMAGE_DIGEST}" >> "$GITHUB_OUTPUT"

  security-and-sign:
    name: Security Scan, SBOM, and Signing
    runs-on: ubuntu-latest
    needs: build-image
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.16.0

      - name: Authenticate to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan image for vulnerabilities
        uses: anchore/grype-action@v0
        with:
          image: ${{ needs.build-image.outputs.image_ref }}@${{ needs.build-image.outputs.image_digest }}
          fail-on-severity: critical
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate SBOM
        env:
          SYFT_REGISTRY_AUTH_USERNAME: ${{ github.actor }}
          SYFT_REGISTRY_AUTH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          syft "${{ needs.build-image.outputs.image_ref }}@${{ needs.build-image.outputs.image_digest }}" -o json > sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      - name: Sign container image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          if [ -z "$COSIGN_PRIVATE_KEY" ]; then
            echo "COSIGN_PRIVATE_KEY secret must be provided" >&2
            exit 1
          fi
          if [ -z "$COSIGN_PASSWORD" ]; then
            echo "COSIGN_PASSWORD secret must be provided" >&2
            exit 1
          fi
          mask_secret() {
            if [ -z "$1" ]; then
              return
            fi
            printf '%s' "$1" | while IFS= read -r line; do
              [ -z "$line" ] && continue
              echo "::add-mask::$line"
            done
          }
          mask_secret "$COSIGN_PRIVATE_KEY"
          mask_secret "$COSIGN_PASSWORD"
          printf '%s' "$COSIGN_PRIVATE_KEY" > cosign.key
          trap 'rm -f cosign.key' EXIT
          cosign sign --key cosign.key "${{ needs.build-image.outputs.image_ref }}@${{ needs.build-image.outputs.image_digest}}"

  validate-externalsecrets:
    name: Validate ExternalSecret Vault Keys
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install pyyaml

      - name: Authenticate to Vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_CI_ROLE_ID }}
          secretId: ${{ secrets.VAULT_CI_SECRET_ID }}
          exportToken: true

      - name: Validate ExternalSecret remote references
        run: python scripts/validate_externalsecret_sources.py deploy/k8s/base/secrets/external-secrets.yaml

  deploy:
    name: Deploy to Linode via Argo CD
    runs-on: ubuntu-latest
    needs:
      - security-and-sign
      - validate-externalsecrets
    steps:
      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 755 argocd /usr/local/bin/argocd

      - name: Argo CD login and sync
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
          ARGOCD_APP: ${{ vars.ARGOCD_APP_NAME }}
        run: |
          if [ -z "$ARGOCD_SERVER" ] || [ -z "$ARGOCD_USERNAME" ] || [ -z "$ARGOCD_PASSWORD" ] || [ -z "$ARGOCD_APP" ]; then
            echo "Argo CD credentials and application name must be provided" >&2
            exit 1
          fi
          argocd login "$ARGOCD_SERVER" --username "$ARGOCD_USERNAME" --password "$ARGOCD_PASSWORD" --insecure
          argocd app set "$ARGOCD_APP" --revision "${GITHUB_SHA}"
          argocd app sync "$ARGOCD_APP"
          argocd app wait "$ARGOCD_APP" --health --timeout 600
