name: OCI Build Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'deploy/docker/**'
      - '.github/workflows/oci-build.yml'

env:
  REGISTRY: ghcr.io/aether

permissions:
  contents: read
  packages: write

jobs:
  kaniko:
    name: Kaniko Build
    runs-on: ubuntu-latest
    if: ${{ hashFiles('deploy/docker/kraken-ws-ingest/Dockerfile') != '' && hashFiles('deploy/docker/risk-api/Dockerfile') != '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GHCR for Kaniko
        env:
          GHCR_USER: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          mkdir -p /kaniko/.docker
          AUTH_TOKEN=$(printf '%s' "${GHCR_USER}:${GHCR_TOKEN}" | base64 | tr -d '\n')
          cat <<EOF >/kaniko/.docker/config.json
          {
            "auths": {
              "ghcr.io": {
                "auth": "${AUTH_TOKEN}"
              }
            }
          }
          EOF
      - name: Build Order Gateway image

        uses: addnab/docker-run-action@v3
        with:
          image: gcr.io/kaniko-project/executor:v1.18.0
          options: >-
            --rm
            -v ${GITHUB_WORKSPACE}:/workspace
            -v /kaniko/.docker:/kaniko/.docker
          run: >-
            /kaniko/executor
            --context /workspace
            --dockerfile /workspace/deploy/docker/kraken-ws-ingest/Dockerfile
            --destination ${REGISTRY}/kraken-ws-ingest:${{ github.sha }}
            --snapshotMode time
            --single-snapshot
      - name: Build Risk API image
        uses: addnab/docker-run-action@v3
        with:
          image: gcr.io/kaniko-project/executor:v1.18.0
          options: >-
            --rm
            -v ${GITHUB_WORKSPACE}:/workspace
            -v /kaniko/.docker:/kaniko/.docker
          run: >-
            /kaniko/executor
            --context /workspace
            --dockerfile /workspace/deploy/docker/risk-api/Dockerfile
            --destination ${REGISTRY}/risk-api:${{ github.sha }}
            --snapshotMode time
            --single-snapshot
  buildah:
    name: Buildah Build
    runs-on: ubuntu-latest
    needs: kaniko
    if: ${{ needs.kaniko.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Buildah
        run: sudo apt-get update && sudo apt-get install -y buildah
      - name: Build Kraken WS Ingest image
        run: |
          buildah bud --layers -f deploy/docker/kraken-ws-ingest/Dockerfile -t ${REGISTRY}/kraken-ws-ingest:${{ github.sha }} .
      - name: Build Risk API image
        run: |
          buildah bud --layers -f deploy/docker/risk-api/Dockerfile -t ${REGISTRY}/risk-api:${{ github.sha }} .
      - name: Push images
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${CR_PAT}" | buildah login --username ${{ github.actor }} --password-stdin ghcr.io
          buildah push ${REGISTRY}/kraken-ws-ingest:${{ github.sha }}
          buildah push ${REGISTRY}/risk-api:${{ github.sha }}
