name: Post-Deploy Smoke Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: read
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run smoke tests
        env:
          BASE_URL: ${{ secrets.STAGING_URL }}
        run: |
          set -euo pipefail
          curl --fail --show-error --silent --location --retry 5 --retry-delay 2 --retry-all-errors \
            "$BASE_URL/healthz"
          curl --fail --show-error --silent --location --retry 5 --retry-delay 2 --retry-all-errors \
            "$BASE_URL/metrics" | grep http_request_duration_seconds
          echo "✅ Smoke tests passed."
