name: Post-Deploy Smoke Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch || github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run smoke tests
        env:
          BASE_URL: ${{ secrets.STAGING_URL }}
        run: |
          set -euo pipefail
          if [ -z "${BASE_URL:-}" ]; then
            echo "STAGING_URL secret is not configured." >&2
            exit 1
          fi
          echo "::add-mask::${BASE_URL}"
          curl --fail --show-error --silent --location --retry 5 --retry-delay 2 --retry-all-errors \
            "$BASE_URL/healthz"
          curl --fail --show-error --silent --location --retry 5 --retry-delay 2 --retry-all-errors \
            "$BASE_URL/metrics" | grep http_request_duration_seconds
          echo "✅ Smoke tests passed."
