name: Post-Deploy Smoke Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: read

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.workflow_run && github.event.workflow_run.pull_requests && github.event.workflow_run.pull_requests[0]
        && github.event.workflow_run.pull_requests[0].number
      || github.event.workflow_run && github.event.workflow_run.head_branch && github.event.workflow_run.head_branch != ''
        && github.event.workflow_run.head_branch
      || github.event.pull_request && github.event.pull_request.number
      || github.head_ref && github.head_ref != '' && github.head_ref
      || github.ref
      || github.event.workflow_run && github.event.workflow_run.run_number
      || github.event.workflow_run && github.event.workflow_run.id
      || github.run_id
    }}
  cancel-in-progress: true



jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run smoke tests
        env:
          BASE_URL: ${{ secrets.STAGING_URL }}
        run: |
          set -euo pipefail
          if [ -z "${BASE_URL:-}" ]; then
            echo "STAGING_URL secret is not configured." >&2
            exit 1
          fi
          echo "::add-mask::${BASE_URL}"
          curl --fail --show-error --silent --location --retry 5 --retry-delay 2 --retry-all-errors \
            --proto '=https' --tlsv1.2 "$BASE_URL/healthz"
          curl --fail --show-error --silent --location --retry 5 --retry-delay 2 --retry-all-errors \
            --proto '=https' --tlsv1.2 "$BASE_URL/metrics" | grep http_request_duration_seconds
          echo "✅ Smoke tests passed."
