name: SBOM and Provenance

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - '**/*.go'
      - 'deploy/**'
      - '.github/workflows/sbom-provenance.yml'

permissions:
  contents: read
  actions: write

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.workflow_run && github.event.workflow_run.pull_requests && github.event.workflow_run.pull_requests[0]
        && github.event.workflow_run.pull_requests[0].number
      || github.event.workflow_run && github.event.workflow_run.head_branch && github.event.workflow_run.head_branch != ''
        && github.event.workflow_run.head_branch
      || github.event.pull_request && github.event.pull_request.number
      || github.head_ref && github.head_ref != '' && github.head_ref
      || github.ref
      || github.event.workflow_run && github.event.workflow_run.id
      || github.run_id
    }}
  cancel-in-progress: true




jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Generate SBOM
        uses: anchore/sbom-action@v0.20.6
        with:
          path: .
          output-file: sbom.spdx.json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
  provenance:
    runs-on: ubuntu-latest
    needs: sbom
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Generate SLSA provenance
        uses: slsa-framework/slsa-github-generator@v2.1.0
        with:
          build-type: https://slsa.dev/container/v0.1
          upload-assets: true
          base-image: ghcr.io/aether/base:1.0.0
