name: Security and Compliance Checks

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  lint-and-test:
    name: Lint and Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install .; fi
          pip install ruff mypy black pytest

      - name: Run Ruff
        run: ruff check .

      - name: Run Black
        run: black --check .

      - name: Run MyPy
        run: mypy .

      - name: Run Pytest
        run: pytest

  trivy-scan:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.14.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"
          exit-code: "1"

  opa-policy-check:
    name: OPA Policy Check
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conftest
        uses: open-policy-agent/setup-conftest@v1
        with:
          version: latest

      - name: Run OPA policies against Kubernetes manifests
        run: |
          set -euo pipefail
          if [ ! -d deploy ]; then
            echo "No Kubernetes manifests found to test."
            exit 0
          fi
          if [ -d policy ]; then
            conftest test deploy
          else
            echo "No OPA policies found. Skipping check."
            exit 0
          fi

  production-approval:
    name: Production Deployment Approval
    runs-on: ubuntu-latest
    needs:
      - trivy-scan
      - opa-policy-check
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
    steps:
      - name: Await manual director approval
        run: |
          echo "Production deployment requires manual director approval via the protected environment."
