name: Security and Compliance Checks

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  lint-and-test:
    name: Lint and Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install .; fi
          pip install ruff mypy black pytest

      - name: Run Ruff
        run: ruff check .

      - name: Run Black
        run: black --check .

      - name: Run MyPy
        run: mypy .

      - name: Run Pytest
        run: pytest

  pip-audit:
    name: Dependency vulnerability scan
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit

      - name: Audit locked dependencies
        run: |
          set -o pipefail
          exit_code=0
          pip-audit \
            --progress-spinner off \
            --config pip-audit.toml \
            --requirement requirements.txt \
            --requirement requirements-ci.txt || exit_code=$?

          if [ "$exit_code" -gt 1 ]; then
            exit "$exit_code"
          fi

          if [ "$exit_code" -eq 1 ]; then
            echo "pip-audit reported vulnerabilities that require manual remediation."
            exit 1
          fi

  trivy-scan:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    needs:
      - lint-and-test
      - pip-audit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.21.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"
          exit-code: "1"

  opa-policy-check:
    name: OPA Policy Check
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Conftest
        env:
          CONFTEST_VERSION: v0.63.0
        run: |
          set -euo pipefail
          archive="conftest_${CONFTEST_VERSION#v}_Linux_x86_64.tar.gz"
          curl -sSL -o "${archive}" "https://github.com/open-policy-agent/conftest/releases/download/${CONFTEST_VERSION}/${archive}"
          tar -xzf "${archive}" conftest
          sudo mv conftest /usr/local/bin/
          rm -f "${archive}"
          conftest --version

      - name: Run OPA policies against Kubernetes manifests
        run: |
          set -euo pipefail
          if [ ! -d deploy ]; then
            echo "No Kubernetes manifests found to test."
            exit 0
          fi
          if [ -d deploy/k8s/policies ]; then
            rego_policies="$(find deploy/k8s/policies -type f -name '*.rego' -print -quit)"
            if [ -n "$rego_policies" ]; then
              conftest test deploy --policy deploy/k8s/policies
            else
              echo "No Rego policies found in deploy/k8s/policies. Skipping check."
              exit 0
            fi
          else
            echo "No OPA policies found at deploy/k8s/policies. Skipping check."
            exit 0
          fi

  production-approval:
    name: Production Deployment Approval
    runs-on: ubuntu-latest
    needs:
      - trivy-scan
      - opa-policy-check
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
    steps:
      - name: Await manual director approval
        run: |
          echo "Production deployment requires manual director approval via the protected environment."
