apiVersion: v1
kind: Service
metadata:
  name: kraken-ws-ingest
  labels:
    app: kraken-ws-ingest
spec:
  selector:
    app: kraken-ws-ingest
  ports:
    - name: metrics
      port: 9000
      targetPort: metrics
